config/routes.rb
Rails.application.routes.draw do
  get 'home/index'

  root 'home#index'

  get 'surveys/search'

  post 'surveys/searchResults'

  get 'surveys/searchResults'

  # This represents a collection of surveys - basically survey class
  resources :surveys

  #resources :posts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
end

app/models/survey.rb
class Survey < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  def new
    #This shows the new Survey page to enter data to create a new record.
    @survey = Survey.new
  end

  def create
    #render plain: params[:survey].inspect
    @survey = Survey.new(survey_params)
    @survey.save
    redirect_to @survey
  end

  def edit
    @survey = Survey.find(params[:id])
  end

  def update
    @survey = Survey.find(params[:id])
    if @survey.update(survey_params)
      redirect_to @survey
    else
      render 'edit'
    end
  end

  def show
    @survey = Survey.find(params[:id])
  end

  def search
  end

  def searchResults
    if params[:city]
      city = params[:city]
      office = params[:office]
      building = params[:building]
      organisation = "Wipro"

      building = building.split(",").first
      floor = 1
      @surveys = Survey.where(organisation: organisation, city: city, office: office, building: building, floor: 1).order(ipms: :desc)
      @queryString = city + ", " + office + ", " + building
      @organisation = organisation
      #send_file Rails.root.join("public", "IPMS1.png"), type: "image/png", disposition: "inline"
      @IPMS1 = "IPMS1.png"
      @IPMS2 = "IPMS2.png"
      @IPMS3 = "IPMS3.png"
      
      # do the calculation part
      @ipms_1_comp_a = @surveys.where(ipms: 1, component: "Comp A").pluck(:area).first.to_f
      @ipms_1_comp_b = @surveys.where(ipms: 1, component: "Comp B").pluck(:area).first.to_f
      @ipms_1_total_area = @ipms_1_comp_a + @ipms_1_comp_b

      @ipms_2_comp_a = @surveys.where(ipms: 2, component: "Comp A").pluck(:area).first.to_f
      @ipms_2_comp_b = @surveys.where(ipms: 2, component: "Comp B").pluck(:area).first.to_f
      @ipms_2_total_area = @ipms_2_comp_a + @ipms_2_comp_b

      @ipms_3_comp_a = @surveys.where(ipms: 3, component: "Comp A").pluck(:area).first.to_f
      @ipms_3_comp_b = @surveys.where(ipms: 3, component: "Comp B").pluck(:area).first.to_f
      @ipms_3_total_area = @ipms_3_comp_a + @ipms_3_comp_b

    else
      render 'search'
    end
  end

  def index
    @surveys = Survey.all
  end

  def destroy
    @survey = Survey.find(params[:id])
    @survey.destroy
    redirect_to surveys_path
  end

  private
  def survey_params
    params.require(:survey).permit(:organisation, :city, :office, :building, :floor, :area, :building_type, :component, :ipms)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/home/index.html.erb
<%= stylesheet_link_tag 'style.css' %>

<!-- script>
var properties = [
	'name',
	'wins',
	'draws',
	'losses',
	'total',
];

$.each( properties, function( i, val ) {

	var orderClass = '';

	$("#" + val).click(function(e){
		e.preventDefault();
		$('.filter__link.filter__link--active').not(this).removeClass('filter__link--active');
  		$(this).toggleClass('filter__link--active');
   		$('.filter__link').removeClass('asc desc');

   		if(orderClass == 'desc' || orderClass == '') {
    			$(this).addClass('asc');
    			orderClass = 'asc';
       	} else {
       		$(this).addClass('desc');
       		orderClass = 'desc';
       	}

		var parent = $(this).closest('.header__item');
    		var index = $(".header__item").index(parent);
		var $table = $('.table-content');
		var rows = $table.find('.table-row').get();
		var isSelected = $(this).hasClass('filter__link--active');
		var isNumber = $(this).hasClass('filter__link--number');

		rows.sort(function(a, b){

			var x = $(a).find('.table-data').eq(index).text();
    			var y = $(b).find('.table-data').eq(index).text();

			if(isNumber == true) {

				if(isSelected) {
					return x - y;
				} else {
					return y - x;
				}

			} else {

				if(isSelected) {
					if(x < y) return -1;
					if(x > y) return 1;
					return 0;
				} else {
					if(x > y) return -1;
					if(x < y) return 1;
					return 0;
				}
			}
    		});

		$.each(rows, function(index,row) {
			$table.append(row);
		});

		return false;
	});

});
</script -->

<br/>

<center>
  <%= image_tag('logo-iconcadd.png') %>
  <h1>Admin Panel</h1>
  <hr/>
  <br/>
  <h2>
    <%= link_to 'My Surveys', controller: 'surveys' %>
  </h2>
</center>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IpmsApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :post_title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body, id: :post_body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>

app/views/surveys/_form.html.erb
<%= form_with(model: @survey) do |form| %>

  <div class="field">
    <%= form.label :organisation %>
    <%= form.text_field :organisation, id: :survey_organisation %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city, id: :survey_city %>
  </div>

  <div class="field">
    <%= form.label :office %>
    <%= form.text_field :office, id: :survey_office %>
  </div>

  <div class="field">
    <%= form.label :building %>
    <%= form.text_field :building, id: :survey_building %>
  </div>

  <div class="field">
    <%= form.label :floor %>
    <%= form.number_field :floor, id: :survey_floor %>
  </div>

   <div class="field">
    <%= form.label :area %>
    <%= form.number_field :area, id: :area, step: :any %>
  </div>

  <div class="field">
    <%= form.label :building_type %>
    <%= form.text_field :building_type, id: :survey_building_type %>
  </div>

  <div class="field">
    <%= form.label :component %>
    <%= form.text_field :component, id: :survey_component %>
  </div>

  <div class="field">
    <%= form.label :ipms %>
    <%= form.text_field :ipms, id: :survey_ipms %>
  </div>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/surveys/edit.html.erb
<center>
  <%= image_tag('logo-iconcadd.png') %>
</center>

<center>
<h1>Edit Survey</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>
</center>

app/views/surveys/index.html.erb
<%= stylesheet_link_tag 'style.css' %>

<center>
  <%= image_tag('logo-iconcadd.png') %>
</center>

<center>
  <h1> Manage Survey Data </h1>
<hr/>
<br/>

<%= link_to 'New Survey', new_survey_path %>
<br>
<br>
<%= link_to 'Search Surveys', 'surveys/search' %>

<h2>Survey List</h2>
</center>

<!-- table border="true">
    <tr>
      <th>Organisation</th>
      <th>City</th>
      <th>Office</th>
      <th>Building</th>
      <th>Floor</th>
      <th>Area</th>
      <th>Building_type</th>
      <th>Component</th>
      <th>IPMS</th>
      <th>Actions</th>
    </tr>
    <hr/>
    <% @surveys.each do |survey| %>
    <tr>
      <td><%= survey.organisation %></td>
      <td><%= survey.city %></td>
      <td><%= survey.office %></td>
      <td><%= survey.building %></td>
      <td><%= survey.floor %></td>
      <td><%= survey.area %></td>
      <td><%= survey.building_type %></td>
      <td><%= survey.component %></td>
      <td><%= survey.ipms %></td>
      <td>
        <%= link_to 'Show', survey_path(survey) %> |
        <%= link_to 'Edit', edit_survey_path(survey) %> |
        <%= link_to 'Delete', survey_path(survey),
              method: :delete,
              data: { confirm: 'Are you sure?' } %>
      </td>
    </tr>
  <% end %>
</table -->


<div class="container">
	<div class="table">
		<div class="table-header">
			<div class="header__item"><a id="Organisation" class="filter__link" href="#">Organisation</a></div>
			<div class="header__item"><a id="City" class="filter__link" href="#">City</a></div>
			<div class="header__item"><a id="Office" class="filter__link" href="#">Office</a></div>
			<div class="header__item"><a id="Building" class="filter__link" href="#">Building</a></div>
			<div class="header__item"><a id="Floor" class="filter__link" href="#">Floor</a></div>
      <div class="header__item"><a id="Floor" class="filter__link" href="#">Area</a></div>
      <div class="header__item"><a id="Floor" class="filter__link" href="#">Building_type</a></div>
      <div class="header__item"><a id="Floor" class="filter__link" href="#">Component</a></div>
      <div class="header__item"><a id="Floor" class="filter__link" href="#">IPMS</a></div>
      <div class="header__item"><a id="Floor" class="filter__link" href="#">Actions</a></div>
		</div>
		<div class="table-content">
      <% @surveys.each do |survey| %>
			<div class="table-row">
				<div class="table-data"><%= survey.organisation %></div>
				<div class="table-data"><%= survey.city %></div>
				<div class="table-data"><%= survey.office %></div>
				<div class="table-data"><%= survey.building %></div>
				<div class="table-data"><%= survey.floor %></div>
        <div class="table-data"><%= survey.area %></div>
        <div class="table-data"><%= survey.building_type %></div>
        <div class="table-data"><%= survey.component %></div>
        <div class="table-data"><%= survey.ipms %></div>
        <div class="table-data">
          <%= link_to 'Show', survey_path(survey) %> |
          <%= link_to 'Edit', edit_survey_path(survey) %> |
          <%= link_to 'Delete', survey_path(survey),method: :delete,data: { confirm: 'Are you sure?' } %>
        </div>
			</div>
      <% end %>
    </div>
	</div>
</div>

app/views/surveys/new.html.erb
<center>
  <%= image_tag('logo-iconcadd.png') %>
</center>

<center>
<h1>Enter New Survey Data</h1>

<%= render 'form' %>

<%= link_to 'Back', surveys_path %>
</center>

app/views/surveys/search.html.erb
<center>
  <%= image_tag('logo-iconcadd.png') %>
</center>

<center>
<h1>Search Surveys</h1>

<hr/>

<br/>
<!-- scope: :survey removed below -->
<%= form_with url: surveys_searchResults_path, local: true do |f| %>

  <%= f.label :city, "Select a city" %>
  <%= f.select :city, ['Bangalore', 'Mysuru', 'Chennai']%>

  <%= f.label :office, "Select office" %>
  <%= f.select :office, ['Wipro Corporate Office, Sarjapur', 'Wipro Tech Ltd, EC1', 'Wipro Tech Ltd, EC2', 'Wipro Tech Ltd, EC3', 'Wipro Tech, Madiwala', 'Wipro Tech, ORR']%>

  <%= f.label :building, "Select Building" %>
  <%= f.select :building, ['Wipro Corporate Office, Level-B2','Wipro Corporate Office, Level-B1', 'Wipro Corporate Office, Level-0', 'Wipro Corporate Office, Level-1', 'Wipro Corporate Office, Level-2', 'Wipro Corporate Office, Level-3']%>

  <%= f.submit "Search" %>
<% end %>

<%= link_to 'Back', surveys_path %>
</center>

app/views/surveys/searchResults.html.erb
<center>
  <%= image_tag('logo-iconcadd.png') %>
</center>

<center>
<h2>IPMS Report for <%= @organisation %></h2>

<hr/>
<br/>

<h3>
  For <%= @queryString %>
</h3>


<!-- table border="true">
    <tr>
      <th>IPMS</th>
      <th>Component</th>
      <th>Area</th>
    </tr>
    <% @surveys.each do |survey| %>
    <tr>
      <td><%= survey.ipms %></td>
      <td><%= survey.component %></td>
      <td><%= survey.area %></td>
    </tr>
    <% end %>
</table -->


<div class="container">
	<div class="table">
		<div class="table-header">
			<div class="header__item"><a id="Organisation" class="filter__link" href="#">IPMS</a></div>
			<div class="header__item"><a id="City" class="filter__link" href="#">ComponentA</a></div>
      <div class="header__item"><a id="City" class="filter__link" href="#">ComponentB</a></div>
			<div class="header__item"><a id="Office" class="filter__link" href="#">Total Area</a></div>
    </div>
		<div class="table-content">
      <%# @surveys.each do |survey| %>
			<div class="table-row">
        <div class="table-data">IPMS 1</div>
        <div class="table-data"><%= @ipms_1_comp_a %></div>
        <div class="table-data"><%= @ipms_1_comp_b %></div>
        <div class="table-data"><%= @ipms_1_total_area %></div>
			</div>
      <div class="table-row">
        <div class="table-data">IPMS 2</div>
        <div class="table-data"><%= @ipms_2_comp_a %></div>
        <div class="table-data"><%= @ipms_2_comp_b %></div>
        <div class="table-data"><%= @ipms_2_total_area %></div>
      </div>
      <div class="table-row">
        <div class="table-data">IPMS 3</div>
        <div class="table-data"><%= @ipms_3_comp_a %></div>
        <div class="table-data"><%= @ipms_3_comp_b %></div>
        <div class="table-data"><%= @ipms_3_total_area %></div>
      </div>
     
      <%# end %>
    </div>
	</div>
</div>



<hr/>


<% if @IPMS1 %>
  <%= image_tag(@IPMS1, size: "300") %>
<% end %>
<% if @IPMS2 %>
  <%= image_tag(@IPMS2, size: "300") %>
<% end %>
<% if @IPMS3 %>
  <%= image_tag(@IPMS3, size: "300") %>
<% end %>
</center>

<%= link_to 'Back', surveys_path %>

app/views/surveys/show.html.erb
<center>
  <%= image_tag('logo-iconcadd.png') %>
</center>

<center>
<h2> Survey Details </h2>

<div>
  <strong>Organisation:</strong>
  <%= @survey.organisation %>
</div>

<div>
  <strong>City:</strong>
  <%= @survey.city %>
</div>

<div>
  <strong>Office:</strong>
  <%= @survey.office %>
</div>

<div>
  <strong>Building:</strong>
  <%= @survey.building %>
</div>

<div>
  <strong>Floor:</strong>
  <%= @survey.floor %>
</div>

<div>
  <strong>Area:</strong>
  <%= @survey.area %>
</div>

<div>
  <strong>Building Type:</strong>
  <%= @survey.building_type %>
</div>

<div>
  <strong>Component:</strong>
  <%= @survey.component %>
</div>

<div>
  <strong>IPMS:</strong>
  <%= @survey.ipms %>
</div>

<%= link_to 'Back', surveys_path %> | <%= link_to 'Edit', edit_survey_path(@survey) %>
</center>